spring:
  application:
    name: pages
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: toto
    password: bob

  jpa:
    hibernate:
      ddl-auto: update
      spring.jpa.properties.hibernate.globally_quoted_identifiers: true
    show-sql: true

  output:
    ansi:
      enabled: ALWAYS
server:
  port: 4242